### ISSUE TITLE
API endpoint returns error for the past 2 months

### ISSUE THREAD

**Issue by mrosseel** [dan-da/bitsquare_market#6]
report from david@blockchainventures.ca :
------------------------------------------
Just a heads up that the API endpoint has been returning an error for the past 2 months or so which has prevented us from gathering data over that period.

Here's an example API call that is failing: https://market.bisq.io/api/trades?market=all&sort=asc&timestamp_from=1503887527&limit=10

Let us know if you need anything from us to help troubleshoot and resolve this.

**Comment by dan-da** [comment]
thx for the report.  This occurs only when market=all.   It broke when we added multiple base currencies.

It will take a little work to make the API return data for all markets across all base currencies.  Either that, or will add a base_currency param.    I should have it fixed in 24 hours.

**Comment by dan-da** [comment]
This is fixed in commit 0cd8a3ff71157486d0c24c4c1a28bbe5249dd5ad.   tag bisq-webservice-api-0.9.11.

No change to the API params.  The results for ?market=all now returns trades across all base currencies.

market.bisq.io site is running the fix.  The example API call that was failing now succeeds.

closing.
