### ISSUE TITLE
Change domain from market.bisq.io => markets.bisq.network

### ISSUE THREAD

**Issue by cbeams** [dan-da/bitsquare_market#7]
- [x] Add DNS entry for markets.bisq.network pointing to 139.59.183.97
- [x] Remove A record for market.bisq.io and replace it with CNAME to markets.bisq.network
- [x] Update the app to accept requests from `Host: markets.bisq.network`
- [x] Provision new Let's Encrypt HTTPs cert to support the change
- [x] Add 301 redirect for `market.bisq.io/*` => `markets.bisq.network/$1`

Note the intentional pluralization of "markets" in the new name.

 - @cbeams will handle the DNS changes, see linked issues below.
 - @emzy is available to help with anything cert-related.

**Comment by dan-da** [comment]
The code also needs to be updated with new domain.  I just grep'ed, and there are only 2 occurrences, plus 2 in the readme.   Anyway, so long as the old domain redirects, it should be ok.

**Comment by dan-da** [comment]
I performed the remaining tasks:
- Update the app to accept requests from Host: markets.bisq.network
- Provision new Let's Encrypt HTTPs cert to support the change
- Add 301 redirect for market.bisq.io/* => markets.bisq.network/$1
- changed market.bisq.io --> markets.bisq.network in app/html.

The following each now redirect to https://markets.bisq.network
- http://markets.bisq.network
- http://market.bisq.io
- https://market.bisq.io
- http://market.bitsquare.io
- http://markets.bitsquare.io

This issue is pretty much done, so I think it can be closed now.    Let me know if any probs...

**Comment by dan-da** [comment]
note:  I also verified that the web api is still working when called from each of the old domains.  There is a redirect now though, so it is possible some poorly written api client might not support redirects and get broken.  anyway, this already happened when we went from market.bitsquare.io to market.bisq.io and we didn't receive any complaints about it.

**Comment by cbeams** [comment]
LGTM, thanks @dan-da. Closing as complete.
